# Dockerfile of Example
# Version 1.0
# Base Images
#FROM registry.cn-hangzhou.aliyuncs.com/yaodefense/defense:3.0.0
FROM registry.cn-hangzhou.aliyuncs.com/yaodefense/attack:3.0.0
#MAINTAINER
MAINTAINER YYD
#ADD . /competition
ADD attack.py /competition
ADD run.sh /competition
WORKDIR /competition
